name: AdsBlockWKWebView
options:
  bundleIdPrefix: at.co.weinmann
  #postGenCommand: pod install
settingGroups:
  preset:
    base:
      DEVELOPMENT_TEAM: NG9KE3E3Q3
      CODE_SIGN_IDENTITY: Apple Distribution
    configs:
      release:
        PROVISIONING_PROFILE_SPECIFIER: 'e754d764-03d6-416f-ba83-203d4ea55fe9'
#packages:
targets:
  AdsBlockWKWebView:
    type: application
    platform: iOS
    deploymentTarget: '10.0'
    sources:
      - path: AdsBlockWKWebView
        excludes:
          - adawayTEST.json
          #- Assets.xcassets/AppIconOld.appiconset
    settings:
      groups:
        - preset
      base:
        SWIFT_VERSION: '4.0'
        #SWIFT_OBJC_BRIDGING_HEADER: B-Header.h
      configs:
        release:
          PROVISIONING_PROFILE_SPECIFIER: '370821b0-f384-4fb3-be72-41f47b8a6126'
    entitlements:
      path: AdsBlockWKWebView/App.entitlements
      properties:
        com.apple.security.application-groups: [group.at.co.weinmann.AdsBlockWKWebView]
    scheme:
      configVariants:
    dependencies:
      - target: AdsBlockWKWebViewShare
        embed: true
      #- package: XYZ
  AdsBlockWKWebViewShare:
    type: app-extension
    platform: iOS
    sources:
      - path: AdsBlockWKWebViewShare
    settings:
      groups:
        - preset
      configs:
        release:
          PROVISIONING_PROFILE_SPECIFIER: 'be6ac4a5-1bd2-42d8-b32c-d01fe9ddeb55'
    info:
      path: AdsBlockWKWebViewShare/Info.plist
      properties:
        NSExtension:
          NSExtensionPrincipalClass: PrincipalClassName
          NSExtensionAttributes:
            NSExtensionPointIdentifier: com.apple.share-services
    entitlements:
      path: AdsBlockWKWebViewShare/App.entitlements
      properties:
        com.apple.security.application-groups: [group.at.co.weinmann.AdsBlockWKWebView]
        com.apple.developer.default-data-protection: NSFileProtectionComplete

