name: AdsBlockWKWebView
options:
  bundleIdPrefix: at.co.weinmann
  #postGenCommand: pod install
#packages:
targets:
  AdsBlockWKWebView:
    type: application
    platform: iOS
    deploymentTarget: '10.0'
    sources:
      - path: AdsBlockWKWebView
        excludes:
          - adawayTEST.json
          #- Assets.xcassets/AppIconOld.appiconset
    settings:
      base:
        DEVELOPMENT_TEAM: NG9KE3E3Q3
        CODE_SIGN_IDENTITY: iPhone Distribution
        SWIFT_VERSION: '4.0'
        #SWIFT_OBJC_BRIDGING_HEADER: B-Header.h
      configs:
        release:
          PROVISIONING_PROFILE_SPECIFIER: '2f778c7d-5d0d-4188-8716-c9f5c32c08c7'
    scheme:
      configVariants:
    #dependencies:
      #- package: XYZ
