name: AdsBlockWKWebView
options:
  minimumXcodeGenVersion: "2.39.1"
  bundleIdPrefix: at.co.weinmann
  deploymentTarget:
    iOS: "10.0"
  #postGenCommand: pod install
#packages:
targets:
  AdsBlockWKWebView:
    type: application
    platform: iOS
    sources:
      - path: AdsBlockWKWebView
        excludes:
          - adawayTEST.json
          #- Assets.xcassets/AppIconOld.appiconset
    settings:
      SWIFT_VERSION: "4.0"
      #SWIFT_OBJC_BRIDGING_HEADER: B-Header.h
    entitlements:
      path: AdsBlockWKWebView/App.entitlements
      properties:
        com.apple.security.application-groups: [group.at.co.weinmann.AdsBlockWKWebView]
    scheme:
      configVariants:
    dependencies:
      - target: AdsBlockWKWebView.Share
      #- package: XYZ
  AdsBlockWKWebView.Share:
    type: app-extension
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: AdsBlockWKWebView_Share
    settings:
      SWIFT_VERSION: "5.9.2"
      CODE_SIGN_ENTITLEMENTS: AdsBlockWKWebView_Share/App.entitlements

