name: AdsBlockWKWebView
options:
  bundleIdPrefix: at.co.weinmann
  #postGenCommand: pod install
#configs:
  #Debug: debug
  #Release: release
settings:
  base:
    DEVELOPMENT_TEAM: NG9KE3E3Q3
    #CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: iPhone Distribution
  #configs:
    #release:
      #PROVISIONING_PROFILE_SPECIFIER: 'e754d764-03d6-416f-ba83-203d4ea55fe9'
#packages:
targets:
  AdsBlockWKWebView:
    type: application
    platform: iOS
    deploymentTarget: '10.0'
    sources:
      - path: AdsBlockWKWebView
        excludes:
          - adawayTEST.json
          #- Assets.xcassets/AppIconOld.appiconset
    settings:
      base:
        #DEVELOPMENT_TEAM: NG9KE3E3Q3
        #CODE_SIGN_IDENTITY: iPhone Distribution
        SWIFT_VERSION: '4.0'
        #SWIFT_OBJC_BRIDGING_HEADER: B-Header.h
      configs:
        release:
          PROVISIONING_PROFILE_SPECIFIER: 'e754d764-03d6-416f-ba83-203d4ea55fe9'
    scheme:
      configVariants:
    dependencies:
      - target: AdsBlockWKWebViewShare
        embed: true
      #- package: XYZ
  AdsBlockWKWebViewShare:
    type: app-extension
    platform: iOS
    sources:
      - path: AdsBlockWKWebViewShare
    info:
      path: AdsBlockWKWebViewShare/Info.plist
      properties:
        NSExtension:
          NSExtensionPrincipalClass: PrincipalClassName
          NSExtensionAttributes:
            NSExtensionPointIdentifier: com.apple.share-services
    entitlements:
      path: AdsBlockWKWebViewShare/App.entitlements
      properties:
        com.apple.developer.default-data-protection: NSFileProtectionComplete
    #scheme:
      #configVariants:

